# Site settings
title: Currency Cloud Technology
email: tech@currencycloud.com
description: > # this means to ignore newlines until "baseurl:"
  A space for the Currency Cloud Tech Team to comment on the general
  state of software development and how we are using the latest tools
  to deliver great code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: CC_Tech_Team
github_username:  currencycloud

# Build settings
markdown: kramdown

exclude: ['Gemfile', 'Gemfile.lock', 's3_website.yml']
